# SPDX-License-Identifier: MIT
# Copyright (c) 2026 friday_gemini_ai

---
name: Lock Merged PRs

on:
  pull_request:
    types: [closed]
  workflow_dispatch:

jobs:
  lock-merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: libnudget/lock@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          days-before-lock: 0
          delete-branch: true
